language: java

jdk:
  - oraclejdk8

script:
  - ./travis.sh

install: true
sudo: false

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar

notifications:
  email: false
  webhooks:
    - secure: "iWBbJ/DPTUTxopx7Q68fS4yNfMFfLOfMhwscKs521Yjl/GQN/HQTQIBCwckwCUssw5iD7sc9tv67JmEk3Jn7ehihdKPKiBUzdXtn0aaqevLkdwARwvGONP5ZMraTog7o9iCUq4dU3/Mtb0exmPmTCrN+GKfKeLdnWOL+R50/ZIs="
  on_start: always
